apiVersion: keycloak.org/v1alpha1
kind: KeycloakBackup
metadata:
  name: example-keycloakbackup
  labels:
    app: sso
spec:
  aws:
    credentialsSecretName: s3-backup
  instanceSelector:
    matchLabels:
      app: sso
